services:
  video-api:
    image: video-api
    container_name: video-api
    platform: linux/amd64
    pull_policy: never
    runtime: nvidia
    user: "1000:1000"
    environment:
      - DD_TRACE_ENABLED=false
      - TARGET_DEVICE=cuda:0
      - PORT=5000
      - STAGE=production
      - DETECTION_TYPE=realscan
    shm_size: "1gb"
    ulimits:
      memlock: -1
    ports:
      - "5003:5000"
    volumes:
      - ./video-requests:/app/requests
      - ./video-results:/app/results
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]

  network-api:
    build: ./network-api
    container_name: network-api
    user: "1000:1000"
    ports:
      - "3333:3000"
    volumes:
      - ./test_images:/app/test_images
      - ./output:/app/output
      - ./audio-requests:/app/test_audio
      - ./audio-results:/app/audio_output
      - ./video-requests:/app/test_video
      - ./video-results:/app/video_output
      - ./uploads:/app/uploads
    depends_on:
      - video-api

